<?php

use Illuminate\Database\Seeder;

class FieldsTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$fields = $this->getFields();

		foreach ($fields as $field) {
			DB::table('fields')->insert([
				'tech'     => $field['tech'],
				'vendor'   => $field['vendor'],
				'db_name'  => $field['db_name'],
				'oss_name' => $field['oss_name'],
			]);
		}
	}

	/**
	 * Available fields by tech and vendor.
	 * 
	 * @return array
	 */
	private function getFields() {
		return [
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c1', 'oss_name' => 'UtranCell pmCellDowntimeAuto' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c2', 'oss_name' => 'UtranCell pmCellDowntimeMan' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c3', 'oss_name' => 'UtranCell pmChSwitchAttemptDchUra' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c4', 'oss_name' => 'UtranCell pmChSwitchAttemptFachUra' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c5', 'oss_name' => 'UtranCell pmChSwitchAttemptHsUra' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c6', 'oss_name' => 'UtranCell pmChSwitchAttemptUraDch' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c7', 'oss_name' => 'UtranCell pmChSwitchAttemptUraFach' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c8', 'oss_name' => 'UtranCell pmChSwitchAttemptUraHs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c9', 'oss_name' => 'UtranCell pmChSwitchSuccDchUra' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c10', 'oss_name' => 'UtranCell pmChSwitchSuccFachUra' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c11', 'oss_name' => 'UtranCell pmChSwitchSuccHsUra' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c12', 'oss_name' => 'UtranCell pmChSwitchSuccUraDch' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c13', 'oss_name' => 'UtranCell pmChSwitchSuccUraFach' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c14', 'oss_name' => 'UtranCell pmChSwitchSuccUraHs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c15', 'oss_name' => 'UtranCell pmDlTrafficVolumePsIntHs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c16', 'oss_name' => 'UtranCell pmDlTrafficVolumePsStrHs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c17', 'oss_name' => 'UtranCell pmNoCellUpdateSuccMultiCs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c18', 'oss_name' => 'UtranCell pmNoCellupdateAttMultiCs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c19', 'oss_name' => 'UtranCell pmNoDirRetryAtt' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c20', 'oss_name' => 'UtranCell pmNoDirRetrySuccess' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c21', 'oss_name' => 'UtranCell pmNoLoadSharingRrcConnCs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c22', 'oss_name' => 'UtranCell pmNoLoadSharingRrcConnPs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c23', 'oss_name' => 'UtranCell pmNoNormalRabReleaseCs64' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c24', 'oss_name' => 'UtranCell pmNoNormalRabReleasePacket' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c25', 'oss_name' => 'UtranCell pmNoNormalRabReleasePacketUra' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c26', 'oss_name' => 'UtranCell pmNoNormalRabReleaseSpeech' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c27', 'oss_name' => 'UtranCell pmNoRabEstAttemptMultiPsInt' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c28', 'oss_name' => 'UtranCell pmNoRabEstAttemptMultiSpeech' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c29', 'oss_name' => 'UtranCell pmNoRabEstAttemptPacketStream' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c30', 'oss_name' => 'UtranCell pmNoRabEstAttemptPktInteractiv' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c31', 'oss_name' => 'UtranCell pmNoRabEstSucPacketInteractive' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c32', 'oss_name' => 'UtranCell pmNoRabEstSuccessMultiPsInt' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c33', 'oss_name' => 'UtranCell pmNoRabEstSuccessMultiSpeech' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c34', 'oss_name' => 'UtranCell pmNoRabEstSuccessPacketStream' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c35', 'oss_name' => 'UtranCell pmNoRabEstablishAttemptCs57' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c36', 'oss_name' => 'UtranCell pmNoRabEstablishAttemptCs64' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c37', 'oss_name' => 'UtranCell pmNoRabEstablishAttemptPacketInteractive' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c38', 'oss_name' => 'UtranCell pmNoRabEstablishAttemptPacketInteractiveHs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c39', 'oss_name' => 'UtranCell pmNoRabEstablishAttemptSpeech' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c40', 'oss_name' => 'UtranCell pmNoRabEstablishSuccessCs57' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c41', 'oss_name' => 'UtranCell pmNoRabEstablishSuccessCs64' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c42', 'oss_name' => 'UtranCell pmNoRabEstablishSuccessPacketInteractive' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c43', 'oss_name' => 'UtranCell pmNoRabEstablishSuccessPacketInteractiveHs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c44', 'oss_name' => 'UtranCell pmNoRabEstablishSuccessSpeech' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c45', 'oss_name' => 'UtranCell pmNoSysRelSpeechNeighbr' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c46', 'oss_name' => 'UtranCell pmNoSysRelSpeechSoHo' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c47', 'oss_name' => 'UtranCell pmNoSysRelSpeechUlSynch' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c48', 'oss_name' => 'UtranCell pmNoSystemRabReleaseCs64' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c49', 'oss_name' => 'UtranCell pmNoSystemRabReleasePacket' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c50', 'oss_name' => 'UtranCell pmNoSystemRabReleasePacketUra' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c51', 'oss_name' => 'UtranCell pmNoSystemRabReleaseSpeech' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c52', 'oss_name' => 'UtranCell pmSamplesBestAmr12200RabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c53', 'oss_name' => 'UtranCell pmSamplesBestAmr4750RabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c54', 'oss_name' => 'UtranCell pmSamplesBestAmr5900RabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c55', 'oss_name' => 'UtranCell pmSamplesBestAmr7950RabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c56', 'oss_name' => 'UtranCell pmSamplesBestAmrNbMmRabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c57', 'oss_name' => 'UtranCell pmSamplesBestAmrWbRabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c58', 'oss_name' => 'UtranCell pmSamplesBestCs12Establish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c59', 'oss_name' => 'UtranCell pmSumBestAmr12200RabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c60', 'oss_name' => 'UtranCell pmSumBestAmr4750RabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c61', 'oss_name' => 'UtranCell pmSumBestAmr5900RabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c62', 'oss_name' => 'UtranCell pmSumBestAmr7950RabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c63', 'oss_name' => 'UtranCell pmSumBestAmrNbMmRabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c64', 'oss_name' => 'UtranCell pmSumBestAmrWbRabEstablish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c65', 'oss_name' => 'UtranCell pmSumBestCs12Establish' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c66', 'oss_name' => 'UtranCell pmTotNoRrcConnectReqCs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c67', 'oss_name' => 'UtranCell pmTotNoRrcConnectReqCsSucc' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c68', 'oss_name' => 'UtranCell pmTotNoRrcConnectReqPs' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c69', 'oss_name' => 'UtranCell pmTotNoRrcConnectReqPsSucc' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c70', 'oss_name' => 'UtranCell pmUlTrafficVolumePsIntEul' ],
			[ 'tech' => '3g', 'vendor' => 'eri', 'db_name' => 'c71', 'oss_name' => 'UtranCell pm_count' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c1', 'oss_name' => 'EUtranCellFDD pmUeCtxtRelCsfbWcdmaEm' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c2', 'oss_name' => 'EUtranCellFDD pmCellDowntimeAuto' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c3', 'oss_name' => 'EUtranCellFDD pmCellDowntimeMan' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c4', 'oss_name' => 'EUtranCellFDD pmErabEstabAttAdded' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c5', 'oss_name' => 'EUtranCellFDD pmErabEstabAttInit' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c6', 'oss_name' => 'EUtranCellFDD pmErabEstabSuccAdded' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c7', 'oss_name' => 'EUtranCellFDD pmErabEstabSuccInit' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c8', 'oss_name' => 'EUtranCellFDD pmErabRelAbnormalEnb' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c9', 'oss_name' => 'EUtranCellFDD pmErabRelAbnormalEnbAct' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c10', 'oss_name' => 'EUtranCellFDD pmErabRelAbnormalMmeAct' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c11', 'oss_name' => 'EUtranCellFDD pmErabRelMme' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c12', 'oss_name' => 'EUtranCellFDD pmErabRelNormalEnb' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c13', 'oss_name' => 'EUtranCellFDD pmPagDiscarded' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c14', 'oss_name' => 'EUtranCellFDD pmPagReceived' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c15', 'oss_name' => 'EUtranCellFDD pmPdcpVolDlDrb' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c16', 'oss_name' => 'EUtranCellFDD pmPdcpVolUlDrb' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c17', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr1' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c18', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr10' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c19', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr11' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c20', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr12' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c21', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr13' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c22', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr14' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c23', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr15' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c24', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr16' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c25', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr2' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c26', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr3' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c27', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr4' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c28', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr5' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c29', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr6' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c30', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr7' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c31', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr8' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c32', 'oss_name' => 'EUtranCellFDD pmRadioRecInterferencePwr9' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c33', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabAttEm' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c34', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabAttHpa' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c35', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabAttMod' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c36', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabAttMta' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c37', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabAttReattEm' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c38', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabAttReattHpa' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c39', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabAttReattMod' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c40', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabAttReattMta' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c41', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabSuccEm' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c42', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabSuccHpa' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c43', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabSuccMod' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c44', 'oss_name' => 'EUtranCellFDD pmRrcConnEstabSuccMta' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c45', 'oss_name' => 'EUtranCellFDD pmS1SigConnEstabAtt' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c46', 'oss_name' => 'EUtranCellFDD pmS1SigConnEstabSucc' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c47', 'oss_name' => 'EUtranCellFDD pmUeCtxtRelCsfbGsm' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c48', 'oss_name' => 'EUtranCellFDD pmUeCtxtRelCsfbGsmEm' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c49', 'oss_name' => 'EUtranCellFDD pmUeCtxtRelCsfbWcdma' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c50', 'oss_name' => 'EUtranCellFDD pmUeCtxtRelSCGsm' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c51', 'oss_name' => 'EUtranCellFDD pmUeCtxtRelSCWcdma' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c52', 'oss_name' => 'EUtranCellRelation pmHoExeSuccLteInterF' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c53', 'oss_name' => 'EUtranCellRelation pmHoExeSuccLteIntraF' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c54', 'oss_name' => 'EUtranCellRelation pmHoExeAttLteInterF' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c55', 'oss_name' => 'EUtranCellRelation pmHoExeAttLteIntraF' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c56', 'oss_name' => 'UtranCellRelation pmHoExeAtt' ],
			[ 'tech' => '4g', 'vendor' => 'eri', 'db_name' => 'c57', 'oss_name' => 'UtranCellRelation pmHoExeSucc' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c1', 'oss_name' => 'cELL.TCH.CALL.DROPS.TA' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c2', 'oss_name' => 'cELL.TCH.CALL.DROPS.UL.RCV.LEVEL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c3', 'oss_name' => 'cELL.TCH.CALL.DROPS.DL.RCV.LEVEL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c4', 'oss_name' => 'cELL.TCH.CALL.DROPS.ULDL.RCV.LEVEL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c5', 'oss_name' => 'cELL.TCH.CALL.DROPS.UL.FER' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c6', 'oss_name' => 'cELL.TCH.CALL.DROPS.DL.FER' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c7', 'oss_name' => 'cELL.TCH.CALL.DROPS.ULDL.FER' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c8', 'oss_name' => 'cELL.TCH.CALL.DROPS.UL.QUAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c9', 'oss_name' => 'cELL.TCH.CALL.DROPS.DL.QUAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c10', 'oss_name' => 'cELL.TCH.CALL.DROPS.ULDL.QUAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c11', 'oss_name' => 'cELL.TCH.CALL.DROPS.OTHER' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c12', 'oss_name' => 'cELL.TRAF.CH.CALL.DROPS' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c13', 'oss_name' => 'cELL.KPI.TCH.ASS.SUCC.TRAF' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c14', 'oss_name' => 'cELL.KPI.TCH.ASS.REQ.TRAF' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c15', 'oss_name' => 'cELL.KPI.SD.SUCC' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c16', 'oss_name' => 'cELL.IMM.ASS.REQ' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c17', 'oss_name' => 'cELL.SIG.CALL.DROPS' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c18', 'oss_name' => 'cELL.KPI.SD.CONGEST' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c19', 'oss_name' => 'cELL.KPI.TCH.TRAF.ERL.TRAF' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c20', 'oss_name' => 'DOWN.CS1.RLC.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c21', 'oss_name' => 'DOWN.CS2.RLC.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c22', 'oss_name' => 'DOWN.CS3.RLC.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c23', 'oss_name' => 'DOWN.CS4.RLC.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c24', 'oss_name' => 'UP.CS1.RLC.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c25', 'oss_name' => 'UP.CS2.RLC.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c26', 'oss_name' => 'UP.CS3.RLC.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c27', 'oss_name' => 'UP.CS4.RLC.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c28', 'oss_name' => 'DOWN.EGPRS.MCS1.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c29', 'oss_name' => 'DOWN.EGPRS.MCS2.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c30', 'oss_name' => 'DOWN.EGPRS.MCS3.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c31', 'oss_name' => 'DOWN.EGPRS.MCS4.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c32', 'oss_name' => 'DOWN.EGPRS.MCS5.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c33', 'oss_name' => 'DOWN.EGPRS.MCS6.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c34', 'oss_name' => 'DOWN.EGPRS.MCS7.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c35', 'oss_name' => 'DOWN.EGPRS.MCS8.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c36', 'oss_name' => 'DOWN.EGPRS.MCS9.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c37', 'oss_name' => 'UP.EGPRS.MCS1.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c38', 'oss_name' => 'UP.EGPRS.MCS2.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c39', 'oss_name' => 'UP.EGPRS.MCS3.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c40', 'oss_name' => 'UP.EGPRS.MCS4.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c41', 'oss_name' => 'UP.EGPRS.MCS5.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c42', 'oss_name' => 'UP.EGPRS.MCS6.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c43', 'oss_name' => 'UP.EGPRS.MCS7.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c44', 'oss_name' => 'UP.EGPRS.MCS8.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c45', 'oss_name' => 'UP.EGPRS.MCS9.RLC.DATA.BLK.VALID.TOTAL' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c46', 'oss_name' => 'cELL.INTERBSC.OUTCELL.HO.SUCC' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c47', 'oss_name' => 'cELL.INTRABSC.OUTCELL.HO.SUCC' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c48', 'oss_name' => 'cELL.INTERBSC.OUTCELL.HO.CMD' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c49', 'oss_name' => 'cELL.INTRABSC.OUTCELL.HO.CMD' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c50', 'oss_name' => 'cELL.INTERBSC.OUTCELL.HO.REQ' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c51', 'oss_name' => 'cELL.INTRABSC.OUTCELL.HO.REQ' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c52', 'oss_name' => 'cELL.INTERRAN.OUTCELL.HO.SUCC' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c53', 'oss_name' => 'cELL.INTERRAN.OUTCELL.HO.CMD' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c54', 'oss_name' => 'cELL.INTERRAN.OUTCELL.HO.REQ' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c55', 'oss_name' => 'cELL.KPI.SD.AVAIL.NUM' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c56', 'oss_name' => 'cELL.KPI.SD.CFG.NUM' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c57', 'oss_name' => 'cELL.KPI.TCH.AVAIL.NUM' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c58', 'oss_name' => 'cELL.KPI.TCH.CFG.NUM' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c59', 'oss_name' => 'cELL.TRX.CFG.AVAIL.NUM' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c60', 'oss_name' => 'cELL.TRX.CFG.NUM' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c61', 'oss_name' => 'TX.DOWN.EGPRS.LLC.PDU.THRPUT.RATE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c62', 'oss_name' => 'TX.DOWN.EGPRS.LLC.PDU.TOTAL.BYTE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c63', 'oss_name' => 'TX.UP.EGPRS.LLC.PDU.THRPUT.RATE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c64', 'oss_name' => 'TX.UP.EGPRS.LLC.PDU.TOTAL.BYTE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c65', 'oss_name' => 'TX.DOWN.GPRS.LLC.PDU.THRPUT.RATE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c66', 'oss_name' => 'TX.DOWN.GPRS.LLC.PDU.TOTAL.BYTE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c67', 'oss_name' => 'TX.UP.GPRS.LLC.PDU.THRPUT.RATE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c68', 'oss_name' => 'TX.UP.GPRS.LLC.PDU.TOTAL.BYTE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c69', 'oss_name' => 'DOWN.EGPRS.TBF.ESTB.ATMP' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c70', 'oss_name' => 'DOWN.GPRS.TBF.ESTB.ATMP' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c71', 'oss_name' => 'UP.EGPRS.TBF.ESTB.ATMP' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c72', 'oss_name' => 'UP.GPRS.TBF.ESTB.ATMP' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c73', 'oss_name' => 'DOWN.EGPRS.TBF.ESTB.FAIL.NO.CHAN.RES' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c74', 'oss_name' => 'DOWN.EGPRS.TBF.ESTB.FAIL.OTHER.CAUSE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c75', 'oss_name' => 'DOWN.GPRS.TBF.ESTB.FAIL.NO.CHAN.RES' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c76', 'oss_name' => 'DOWN.GPRS.TBF.ESTB.FAIL.OTHER.CAUSE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c77', 'oss_name' => 'UP.EGPRS.TBF.ESTB.FAIL.NO.CHAN.RES' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c78', 'oss_name' => 'UP.EGPRS.TBF.ESTB.FAIL.OTHER.CAUSE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c79', 'oss_name' => 'UP.GPRS.TBF.ESTB.FAIL.NO.CHAN.RES' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c80', 'oss_name' => 'UP.GPRS.TBF.ESTB.FAIL.OTHER.CAUSE' ],
			[ 'tech' => '2g', 'vendor' => 'hua', 'db_name' => 'c81', 'oss_name' => 'cELL.SD.SUCC.CALL' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c1', 'oss_name' => 'VS.RAB.AbnormRel.CS64' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c2', 'oss_name' => 'VS.RAB.AbnormRel.AMRWB' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c3', 'oss_name' => 'VS.RAB.AbnormRel.AMR' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c4', 'oss_name' => 'VS.RAB.NormRel.CS64' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c5', 'oss_name' => 'VS.RAB.NormRel.AMRWB' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c6', 'oss_name' => 'VS.RAB.NormRel.AMR' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c7', 'oss_name' => 'VS.RAB.AbnormRel.PS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c8', 'oss_name' => 'VS.RAB.AbnormRel.PS.PCH' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c9', 'oss_name' => 'VS.RAB.AbnormRel.PS.F2P' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c10', 'oss_name' => 'VS.RAB.AbnormRel.PS.D2P' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c11', 'oss_name' => 'VS.RAB.NormRel.PS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c12', 'oss_name' => 'VS.RAB.NormRel.PS.PCH' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c13', 'oss_name' => 'VS.DCCC.D2P.Succ' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c14', 'oss_name' => 'VS.DCCC.Succ.F2U' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c15', 'oss_name' => 'VS.DCCC.Succ.D2U' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c16', 'oss_name' => 'RRC.SuccConnEstab.EmgCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c17', 'oss_name' => 'RRC.SuccConnEstab.OrgConvCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c18', 'oss_name' => 'RRC.SuccConnEstab.TmConvCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c19', 'oss_name' => 'RRC.AttConnEstab.EmgCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c20', 'oss_name' => 'RRC.AttConnEstab.OrgConvCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c21', 'oss_name' => 'RRC.AttConnEstab.TmConvCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c22', 'oss_name' => 'VS.RAB.SuccEstabCS.AMRWB' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c23', 'oss_name' => 'VS.RAB.SuccEstabCS.AMR' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c24', 'oss_name' => 'VS.IRATHO.SuccOutCS.DR' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c25', 'oss_name' => 'VS.SuccEstabCS.PSinDCH' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c26', 'oss_name' => 'VS.SuccEstabCS.PSinFACH' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c27', 'oss_name' => 'VS.RAB.AttEstab.AMR' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c28', 'oss_name' => 'VS.RAB.AttEstabCS.AMRWB' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c29', 'oss_name' => 'VS.AttEstabCS.PSinDCH' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c30', 'oss_name' => 'VS.AttEstabCS.PSinFACH' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c31', 'oss_name' => 'VS.SuccPSP2D.CSConv' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c32', 'oss_name' => 'VS.AttPSP2D.CSConv' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c33', 'oss_name' => 'RRC.SuccConnEstab.OrgHhPrSig' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c34', 'oss_name' => 'RRC.SuccConnEstab.OrgBkgCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c35', 'oss_name' => 'RRC.SuccConnEstab.OrgInterCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c36', 'oss_name' => 'RRC.SuccConnEstab.OrgStrCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c37', 'oss_name' => 'RRC.SuccConnEstab.OrgSubCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c38', 'oss_name' => 'RRC.SuccConnEstab.TmBkgCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c39', 'oss_name' => 'RRC.SuccConnEstab.TmHhPrSig' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c40', 'oss_name' => 'RRC.SuccConnEstab.TmItrCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c41', 'oss_name' => 'RRC.SuccConnEstab.TmStrCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c42', 'oss_name' => 'RRC.AttConnEstab.OrgHhPrSig' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c43', 'oss_name' => 'RRC.AttConnEstab.OrgSubCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c44', 'oss_name' => 'RRC.AttConnEstab.OrgBkgCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c45', 'oss_name' => 'RRC.AttConnEstab.OrgInterCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c46', 'oss_name' => 'RRC.AttConnEstab.OrgStrCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c47', 'oss_name' => 'RRC.AttConnEstab.TmBkgCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c48', 'oss_name' => 'RRC.AttConnEstab.TmHhPrSig' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c49', 'oss_name' => 'RRC.AttConnEstab.TmInterCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c50', 'oss_name' => 'RRC.AttConnEstab.TmStrCall' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c51', 'oss_name' => 'VS.RAB.SuccEstabPS.Str' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c52', 'oss_name' => 'VS.RAB.SuccEstabPS.Int' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c53', 'oss_name' => 'VS.RAB.SuccEstabPS.Conv' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c54', 'oss_name' => 'VS.RAB.SuccEstabPS.Bkg' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c55', 'oss_name' => 'VS.MultiRAB.SuccEstab.CSPS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c56', 'oss_name' => 'VS.MultiRAB.SuccEstab.PSPS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c57', 'oss_name' => 'VS.RAB.AttEstabPS.Str' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c58', 'oss_name' => 'VS.RAB.AttEstabPS.Int' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c59', 'oss_name' => 'VS.RAB.AttEstabPS.Conv' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c60', 'oss_name' => 'VS.RAB.AttEstabPS.Bkg' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c61', 'oss_name' => 'VS.MultiRAB.AttEstab.CSPS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c62', 'oss_name' => 'VS.MultiRAB.AttEstab.PSPS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c63', 'oss_name' => 'VS.DCCC.P2D.Succ' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c64', 'oss_name' => 'VS.DCCC.P2F.Succ' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c65', 'oss_name' => 'VS.DCCC.URAP2D.Succ' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c66', 'oss_name' => 'VS.DCCC.URAP2F.Succ' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c67', 'oss_name' => 'VS.DCCC.P2D.Att' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c68', 'oss_name' => 'VS.DCCC.P2F.Att' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c69', 'oss_name' => 'VS.DCCC.URAP2D.Att' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c70', 'oss_name' => 'VS.DCCC.URAP2F.Att' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c71', 'oss_name' => 'VS.HSDPA.RAB.AttEstab' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c72', 'oss_name' => 'VS.HSDPA.RAB.SuccEstab' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c73', 'oss_name' => 'VS.RAB.AMR.Erlang.cell' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c74', 'oss_name' => 'VS.HSDPA.MeanChThroughput.TotalBytes' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c75', 'oss_name' => 'VS.HSUPA.MeanChThroughput.TotalBytes' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c76', 'oss_name' => 'VS.MeanRTWP' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c77', 'oss_name' => 'VS.HSDPA.DataOutput.TRB' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c78', 'oss_name' => 'VS.HSDPA.DataTtiNum.TRB' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c79', 'oss_name' => 'VS.HSDPA.DataTtiNum.User' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c80', 'oss_name' => 'VS.HSDPA.DCCfg.DualCarrierActedNum' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c81', 'oss_name' => 'VS.SHO.AMR.Succ' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c82', 'oss_name' => 'VS.SHO.AMR.Att' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c83', 'oss_name' => 'VS.SHO.PS.Succ' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c84', 'oss_name' => 'VS.SHO.PS.Att' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c85', 'oss_name' => 'VS.HHO.SuccInterFreqOut.CS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c86', 'oss_name' => 'VS.HHO.AttInterFreqOut.CS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c87', 'oss_name' => 'VS.HHO.SuccInterFreqOut.PS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c88', 'oss_name' => 'VS.HHO.AttInterFreqOut.PS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c89', 'oss_name' => 'IRATHO.SuccOutCS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c90', 'oss_name' => 'IRATHO.AttOutCS' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c91', 'oss_name' => 'VS.HSDPA.InactiveDataTtiNum.TRB' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c92', 'oss_name' => 'VS.Cell.UnavailTime' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c93', 'oss_name' => 'VS.Cell.UnavailTime.NodeBBLK' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c94', 'oss_name' => 'VS.Cell.UnavailTime.Sys' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c95', 'oss_name' => 'VS.Cell.HSDPA.UnavailTime' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c96', 'oss_name' => 'VS.Cell.HSUPA.UnavailTime' ],
			[ 'tech' => '3g', 'vendor' => 'hua', 'db_name' => 'c97', 'oss_name' => 'VS.DCCC.Succ.F2P' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c1', 'oss_name' => 'L.E-RAB.AbnormRel' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c2', 'oss_name' => 'L.E-RAB.AbnormRel.MME' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c3', 'oss_name' => 'L.E-RAB.NormRel' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c4', 'oss_name' => 'L.IRATHO.E2W.ExecSuccOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c5', 'oss_name' => 'L.E-RAB.AbnormRel.Radio' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c6', 'oss_name' => 'L.E-RAB.AbnormRel.TNL' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c7', 'oss_name' => 'L.E-RAB.AbnormRel.Cong' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c8', 'oss_name' => 'L.E-RAB.AbnormRel.HOFailure' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c9', 'oss_name' => 'L.E-RAB.AttEst' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c10', 'oss_name' => 'L.E-RAB.SuccEst' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c11', 'oss_name' => 'L.RRC.ConnReq.Att.Emc' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c12', 'oss_name' => 'L.RRC.ConnReq.Att.HighPri' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c13', 'oss_name' => 'L.RRC.ConnReq.Att.Mt' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c14', 'oss_name' => 'L.RRC.ConnReq.Att.MoData' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c15', 'oss_name' => 'L.RRC.ConnReq.Succ.Emc' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c16', 'oss_name' => 'L.RRC.ConnReq.Succ.HighPri' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c17', 'oss_name' => 'L.RRC.ConnReq.Succ.Mt' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c18', 'oss_name' => 'L.RRC.ConnReq.Succ.MoData' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c19', 'oss_name' => 'L.S1Sig.ConnEst.Succ' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c20', 'oss_name' => 'L.S1Sig.ConnEst.Att' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c21', 'oss_name' => 'L.Paging.UU.Succ' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c22', 'oss_name' => 'L.Paging.UU.Att' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c23', 'oss_name' => 'L.Thrp.bits.DL' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c24', 'oss_name' => 'L.Thrp.bits.UL' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c25', 'oss_name' => 'L.CSFB.E2w' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c26', 'oss_name' => 'L.CSFB.E2g' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c27', 'oss_name' => 'L.IRATHO.E2W.ExecAttOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c28', 'oss_name' => 'L.HHO.IntraeNB.IntraFreq.ExecSuccOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c29', 'oss_name' => 'L.HHO.IntereNB.IntraFreq.ExecSuccOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c30', 'oss_name' => 'L.HHO.IntraeNB.InterFreq.ExecSuccOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c31', 'oss_name' => 'L.HHO.IntereNB.InterFreq.ExecSuccOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c32', 'oss_name' => 'L.HHO.IntraeNB.IntraFreq.ExecAttOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c33', 'oss_name' => 'L.HHO.IntereNB.IntraFreq.ExecAttOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c34', 'oss_name' => 'L.HHO.IntraeNB.InterFreq.ExecAttOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c35', 'oss_name' => 'L.HHO.IntereNB.InterFreq.ExecAttOut' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c36', 'oss_name' => 'L.Cell.Unavail.Dur.Sys' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c37', 'oss_name' => 'L.Cell.Unavail.Dur.Manual' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c38', 'oss_name' => 'L.UL.Interference.PUSCH.Index0' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c39', 'oss_name' => 'L.UL.Interference.PUSCH.Index1' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c40', 'oss_name' => 'L.UL.Interference.PUSCH.Index2' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c41', 'oss_name' => 'L.UL.Interference.PUSCH.Index3' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c42', 'oss_name' => 'L.UL.Interference.PUSCH.Index4' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c43', 'oss_name' => 'L.UL.Interference.PUSCH.Index5' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c44', 'oss_name' => 'L.UL.Interference.PUSCH.Index6' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c45', 'oss_name' => 'L.UL.Interference.PUSCH.Index7' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c46', 'oss_name' => 'L.UL.Interference.PUSCH.Index8' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c47', 'oss_name' => 'L.UL.Interference.PUSCH.Index9' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c48', 'oss_name' => 'L.UL.Interference.PUSCH.Index10' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c49', 'oss_name' => 'L.UL.Interference.PUSCH.Index11' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c50', 'oss_name' => 'L.UL.Interference.PUSCH.Index12' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c51', 'oss_name' => 'L.UL.Interference.PUSCH.Index13' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c52', 'oss_name' => 'L.UL.Interference.PUSCH.Index14' ],
			[ 'tech' => '4g', 'vendor' => 'hua', 'db_name' => 'c53', 'oss_name' => 'L.UL.Interference.PUSCH.Index15' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c1', 'oss_name' => 'cELLCCHHO pmCCHHOCNT' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c2', 'oss_name' => 'cELLGPRS3 pmDLGMMVOL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c3', 'oss_name' => 'cELLGPRS3 pmULGMMVOL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c4', 'oss_name' => 'cELLQOSEG pmDLBGEGDATA' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c5', 'oss_name' => 'cELLQOSEG pmULBGEGDATA' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c6', 'oss_name' => 'cELLQOSG pmDLBGGDATA' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c7', 'oss_name' => 'cELLQOSG pmULBGGDATA' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c8', 'oss_name' => 'cELTCHF pmTFCASSALL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c9', 'oss_name' => 'cELTCHF pmTFCASSALLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c10', 'oss_name' => 'cELTCHF pmTFNDROP' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c11', 'oss_name' => 'cELTCHF pmTFNDROPSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c12', 'oss_name' => 'cELTCHF pmTFNRELCONG' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c13', 'oss_name' => 'cELTCHF pmTFNRELCONGSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c14', 'oss_name' => 'cELTCHF pmTFNSCAN' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c15', 'oss_name' => 'cELTCHF pmTFTRALACC' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c16', 'oss_name' => 'cELTCHF pm_count' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c17', 'oss_name' => 'cELTCHH pmTHCASSALL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c18', 'oss_name' => 'cELTCHH pmTHCASSALLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c19', 'oss_name' => 'cELTCHH pmTHNDROP' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c20', 'oss_name' => 'cELTCHH pmTHNDROPSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c21', 'oss_name' => 'cELTCHH pmTHNRELCONG' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c22', 'oss_name' => 'cELTCHH pmTHNRELCONGSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c23', 'oss_name' => 'cELTCHH pmTHNSCAN' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c24', 'oss_name' => 'cELTCHH pmTHTRALACC' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c25', 'oss_name' => 'cELTCHH pm_count' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c26', 'oss_name' => 'cLSDCCH pmCCONGS' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c27', 'oss_name' => 'cLSDCCH pmCMSESTAB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c28', 'oss_name' => 'cLSDCCH pmCNDROP' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c29', 'oss_name' => 'cLSDCCH pmCNRELCONG' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c30', 'oss_name' => 'cLSDCCHO pmCCONGSSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c31', 'oss_name' => 'cLSDCCHO pmCNRELCONGSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c32', 'oss_name' => 'cLTCH pmTASSALL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c33', 'oss_name' => 'cLTCH pmTCASSALL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c34', 'oss_name' => 'cLTCHDRF pmTFDISQABL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c35', 'oss_name' => 'cLTCHDRF pmTFDISQABLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c36', 'oss_name' => 'cLTCHDRF pmTFDISQADL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c37', 'oss_name' => 'cLTCHDRF pmTFDISQADLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c38', 'oss_name' => 'cLTCHDRF pmTFDISQAUL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c39', 'oss_name' => 'cLTCHDRF pmTFDISQAULSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c40', 'oss_name' => 'cLTCHDRF pmTFDISSBL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c41', 'oss_name' => 'cLTCHDRF pmTFDISSBLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c42', 'oss_name' => 'cLTCHDRF pmTFDISSDL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c43', 'oss_name' => 'cLTCHDRF pmTFDISSDLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c44', 'oss_name' => 'cLTCHDRF pmTFDISSUL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c45', 'oss_name' => 'cLTCHDRF pmTFDISSULSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c46', 'oss_name' => 'cLTCHDRF pmTFDISTA' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c47', 'oss_name' => 'cLTCHDRF pmTFSUDLOS' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c48', 'oss_name' => 'cLTCHDRF pmTFSUDLOSSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c49', 'oss_name' => 'cLTCHDRH pmTHDISQABL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c50', 'oss_name' => 'cLTCHDRH pmTHDISQABLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c51', 'oss_name' => 'cLTCHDRH pmTHDISQADL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c52', 'oss_name' => 'cLTCHDRH pmTHDISQADLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c53', 'oss_name' => 'cLTCHDRH pmTHDISQAUL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c54', 'oss_name' => 'cLTCHDRH pmTHDISQAULSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c55', 'oss_name' => 'cLTCHDRH pmTHDISSBL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c56', 'oss_name' => 'cLTCHDRH pmTHDISSBLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c57', 'oss_name' => 'cLTCHDRH pmTHDISSDL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c58', 'oss_name' => 'cLTCHDRH pmTHDISSDLSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c59', 'oss_name' => 'cLTCHDRH pmTHDISSUL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c60', 'oss_name' => 'cLTCHDRH pmTHDISSULSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c61', 'oss_name' => 'cLTCHDRH pmTHDISTA' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c62', 'oss_name' => 'cLTCHDRH pmTHSUDLOS' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c63', 'oss_name' => 'cLTCHDRH pmTHSUDLOSSUB' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c64', 'oss_name' => 'cLTCHFV3 pmTFV3NSCAN' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c65', 'oss_name' => 'cLTCHFV3 pmTFV3TRALACC' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c66', 'oss_name' => 'cLTCHFV3 pm_count' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c67', 'oss_name' => 'cLTCHHV3 pmTHV3NSCAN' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c68', 'oss_name' => 'cLTCHHV3 pmTHV3TRALACC' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c69', 'oss_name' => 'cLTCHHV3 pm_count' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c70', 'oss_name' => 'DOWNTIME pmTDWNACC' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c71', 'oss_name' => 'DOWNTIME pmTDWNSCAN' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c72', 'oss_name' => 'NCELLREL pmHOVERCNT' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c73', 'oss_name' => 'NCELLREL pmHOVERSUC' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c74', 'oss_name' => 'NECELLREL pmHOVERCNT' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c75', 'oss_name' => 'NECELLREL pmHOVERSUC' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c76', 'oss_name' => 'RANDOMACC pmRAANPAG' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c77', 'oss_name' => 'RANDOMACC pmRAEMCAL' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c78', 'oss_name' => 'RANDOMACC pmRAOSREQ' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c79', 'oss_name' => 'RANDOMACC pmRAOTHER' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c80', 'oss_name' => 'RNDACCEXT pmRAAPAG1' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c81', 'oss_name' => 'RNDACCEXT pmRAAPAG2' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c82', 'oss_name' => 'RNDACCEXT pmRAAPOPS' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c83', 'oss_name' => 'RNDACCEXT pmRAORDAT' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c84', 'oss_name' => 'RNDACCEXT pmRAORSPE' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c85', 'oss_name' => 'cELLGPRS pmFAILDLTBFEST' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c86', 'oss_name' => 'cELLGPRS2 pmPREJTFI' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c87', 'oss_name' => 'cELLGPRS2 pmPREJOTH' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c88', 'oss_name' => 'cELLGPRS2 pmPSCHREQ' ],
			[ 'tech' => '2g', 'vendor' => 'eri', 'db_name' => 'c89', 'oss_name' => 'cELLGPRS pmDLTBFEST' ]
		];
	}
}
